/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Desafio2_mentoria_Banrisul;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
